# Generated by Django 4.1.2 on 2023-03-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_product_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="chead0",
            field=models.CharField(default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="chead1",
            field=models.CharField(default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="chead2",
            field=models.CharField(default="", max_length=5000),
        ),
    ]
