# Generated by Django 4.1.2 on 2023-03-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_chead0_blogpost_chead1_blogpost_chead2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="thumbnail",
            field=models.ImageField(default="", upload_to="blog/images"),
        ),
    ]
