# Generated by Django 4.1.2 on 2023-02-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_category_product_image_product_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_id",
            new_name="id",
        ),
    ]
