# Generated by Django 4.1.2 on 2023-02-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(default="", max_length=90),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.CharField(default="", max_length=90),
        ),
        migrations.AlterField(
            model_name="order",
            name="items_json",
            field=models.CharField(default="", max_length=5000),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(default="", max_length=90),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(default="", max_length=90),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip_code",
            field=models.CharField(default="", max_length=30),
        ),
    ]
