# Generated by Django 4.1.2 on 2023-03-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_order_phone_alter_order_address_alter_order_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=models.CharField(max_length=5000),
        ),
    ]
