# Generated by Django 4.1.2 on 2023-03-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_orderupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
